//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaMagisk.Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NinjaMagisk.Interface.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 32-bit 的本地化字符串。
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 64-bit 的本地化字符串。
        /// </summary>
        public static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows activated 的本地化字符串。
        /// </summary>
        public static string _ACTIVE_WINDOWS {
            get {
                return ResourceManager.GetString("_ACTIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new line 的本地化字符串。
        /// </summary>
        public static string _ADD_NEW_LINE {
            get {
                return ResourceManager.GetString("_ADD_NEW_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 answer 的本地化字符串。
        /// </summary>
        public static string _ANSWER {
            get {
                return ResourceManager.GetString("_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User canceled action 的本地化字符串。
        /// </summary>
        public static string _CANCEL_OP {
            get {
                return ResourceManager.GetString("_CANCEL_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot activate Windows 的本地化字符串。
        /// </summary>
        public static string _CANNOT_ACTIVE_WINDOWS {
            get {
                return ResourceManager.GetString("_CANNOT_ACTIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot clear log file 的本地化字符串。
        /// </summary>
        public static string _CANNOT_CLEAR_LOGFILE {
            get {
                return ResourceManager.GetString("_CANNOT_CLEAR_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot disable Windows Security Center 的本地化字符串。
        /// </summary>
        public static string _CANNOT_DISABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_CANNOT_DISABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot disable Windows Update 的本地化字符串。
        /// </summary>
        public static string _CANNOT_DISABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_CANNOT_DISABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot disable/enable hibernate 的本地化字符串。
        /// </summary>
        public static string _CANNOT_DISENABLE_HIBERNATE {
            get {
                return ResourceManager.GetString("_CANNOT_DISENABLE_HIBERNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot enable high-performance power plan 的本地化字符串。
        /// </summary>
        public static string _CANNOT_ENABLE_HIGHPOWERCFG {
            get {
                return ResourceManager.GetString("_CANNOT_ENABLE_HIGHPOWERCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot enable Windows Security Center 的本地化字符串。
        /// </summary>
        public static string _CANNOT_ENABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_CANNOT_ENABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot enable Windows Update 的本地化字符串。
        /// </summary>
        public static string _CANNOT_ENABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_CANNOT_ENABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write to log file 的本地化字符串。
        /// </summary>
        public static string _CANNOT_WRITE_LOGFILE {
            get {
                return ResourceManager.GetString("_CANNOT_WRITE_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear log file 的本地化字符串。
        /// </summary>
        public static string _CLEAR_LOGFILE {
            get {
                return ResourceManager.GetString("_CLEAR_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create directory 的本地化字符串。
        /// </summary>
        public static string _CREATE_DIRECTORY {
            get {
                return ResourceManager.GetString("_CREATE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current version 的本地化字符串。
        /// </summary>
        public static string _CURRENT_VER {
            get {
                return ResourceManager.GetString("_CURRENT_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable aria2c log output 的本地化字符串。
        /// </summary>
        public static string _DISABLE_ARIA2C_LOG_OUTPUT {
            get {
                return ResourceManager.GetString("_DISABLE_ARIA2C_LOG_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Security Center disabled 的本地化字符串。
        /// </summary>
        public static string _DISABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_DISABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Update disabled 的本地化字符串。
        /// </summary>
        public static string _DISABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_DISABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hibernate disabled/enabled 的本地化字符串。
        /// </summary>
        public static string _DISENABLE_HIBERNATE {
            get {
                return ResourceManager.GetString("_DISENABLE_HIBERNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download complete 的本地化字符串。
        /// </summary>
        public static string _DOWNLOADING_COMPLETE {
            get {
                return ResourceManager.GetString("_DOWNLOADING_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download failed 的本地化字符串。
        /// </summary>
        public static string _DOWNLOADING_FAILED {
            get {
                return ResourceManager.GetString("_DOWNLOADING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading file 的本地化字符串。
        /// </summary>
        public static string _DOWNLOADING_FILE {
            get {
                return ResourceManager.GetString("_DOWNLOADING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable aria2c log output 的本地化字符串。
        /// </summary>
        public static string _ENABLE_ARIA2C_LOG_OUTPUT {
            get {
                return ResourceManager.GetString("_ENABLE_ARIA2C_LOG_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High-performance power plan enabled 的本地化字符串。
        /// </summary>
        public static string _ENABLE_HIGHPOWERCFG {
            get {
                return ResourceManager.GetString("_ENABLE_HIGHPOWERCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Security Center enabled 的本地化字符串。
        /// </summary>
        public static string _ENABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_ENABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Update enabled 的本地化字符串。
        /// </summary>
        public static string _ENABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_ENABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter your credentials 的本地化字符串。
        /// </summary>
        public static string _ENTER_CREDENTIALS {
            get {
                return ResourceManager.GetString("_ENTER_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string _ERROR {
            get {
                return ResourceManager.GetString("_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error code 的本地化字符串。
        /// </summary>
        public static string _ERROR_CODE {
            get {
                return ResourceManager.GetString("_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File exists 的本地化字符串。
        /// </summary>
        public static string _FILE_EXIST {
            get {
                return ResourceManager.GetString("_FILE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File saved to 的本地化字符串。
        /// </summary>
        public static string _FILE_EXIST_PATH {
            get {
                return ResourceManager.GetString("_FILE_EXIST_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing file 的本地化字符串。
        /// </summary>
        public static string _FILE_WRITING {
            get {
                return ResourceManager.GetString("_FILE_WRITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get HTML element 的本地化字符串。
        /// </summary>
        public static string _FIND_HTML_CODE {
            get {
                return ResourceManager.GetString("_FIND_HTML_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing HTML page file 的本地化字符串。
        /// </summary>
        public static string _FINDING_HTML_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("_FINDING_HTML_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get 32-bit download link 的本地化字符串。
        /// </summary>
        public static string _GET_32_LINK {
            get {
                return ResourceManager.GetString("_GET_32_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get 64-bit download link 的本地化字符串。
        /// </summary>
        public static string _GET_64_LINK {
            get {
                return ResourceManager.GetString("_GET_64_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get aria2c arguments 的本地化字符串。
        /// </summary>
        public static string _GET_ARIA2C_ARGS {
            get {
                return ResourceManager.GetString("_GET_ARIA2C_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get aria2c exitcode 的本地化字符串。
        /// </summary>
        public static string _GET_ARIA2C_EXITCODE {
            get {
                return ResourceManager.GetString("_GET_ARIA2C_EXITCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get aria2c file path 的本地化字符串。
        /// </summary>
        public static string _GET_ARIA2C_PATH {
            get {
                return ResourceManager.GetString("_GET_ARIA2C_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get directory 的本地化字符串。
        /// </summary>
        public static string _GET_DIRECTORY {
            get {
                return ResourceManager.GetString("_GET_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get file 的本地化字符串。
        /// </summary>
        public static string _GET_FILE {
            get {
                return ResourceManager.GetString("_GET_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get all files in directory 的本地化字符串。
        /// </summary>
        public static string _GET_FILES_IN_DIRECTORY {
            get {
                return ResourceManager.GetString("_GET_FILES_IN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get html file 的本地化字符串。
        /// </summary>
        public static string _GET_HTML {
            get {
                return ResourceManager.GetString("_GET_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get output directory 的本地化字符串。
        /// </summary>
        public static string _GET_OUTPUT_DIRECTORY {
            get {
                return ResourceManager.GetString("_GET_OUTPUT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get output file name 的本地化字符串。
        /// </summary>
        public static string _GET_OUTPUT_NAME {
            get {
                return ResourceManager.GetString("_GET_OUTPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Response 的本地化字符串。
        /// </summary>
        public static string _GET_RESPONSE {
            get {
                return ResourceManager.GetString("_GET_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get project resource manifest 的本地化字符串。
        /// </summary>
        public static string _GET_RM_NAME {
            get {
                return ResourceManager.GetString("_GET_RM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get resource data 的本地化字符串。
        /// </summary>
        public static string _GET_RM_OBJ {
            get {
                return ResourceManager.GetString("_GET_RM_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get system bit 的本地化字符串。
        /// </summary>
        public static string _GET_SYSTEM_BIT {
            get {
                return ResourceManager.GetString("_GET_SYSTEM_BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get temp folder 的本地化字符串。
        /// </summary>
        public static string _GET_TEMP {
            get {
                return ResourceManager.GetString("_GET_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get download URL 的本地化字符串。
        /// </summary>
        public static string _GET_URL {
            get {
                return ResourceManager.GetString("_GET_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing JSON failed 的本地化字符串。
        /// </summary>
        public static string _JSON_PARSING_FAILED {
            get {
                return ResourceManager.GetString("_JSON_PARSING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest version 的本地化字符串。
        /// </summary>
        public static string _LATEST_VERSION {
            get {
                return ResourceManager.GetString("_LATEST_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login error or password 的本地化字符串。
        /// </summary>
        public static string _LOGIN_ERROR_USER_OR_PASSWORD {
            get {
                return ResourceManager.GetString("_LOGIN_ERROR_USER_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify your identity 的本地化字符串。
        /// </summary>
        public static string _LOGIN_VERIFY {
            get {
                return ResourceManager.GetString("_LOGIN_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation failed 的本地化字符串。
        /// </summary>
        public static string _LOGIN_VERIFY_ERROR {
            get {
                return ResourceManager.GetString("_LOGIN_VERIFY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create ResourceManager instance 的本地化字符串。
        /// </summary>
        public static string _NEW_RM {
            get {
                return ResourceManager.GetString("_NEW_RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version available 的本地化字符串。
        /// </summary>
        public static string _NEW_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("_NEW_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current version is the latest. 的本地化字符串。
        /// </summary>
        public static string _NON_NEW_VER {
            get {
                return ResourceManager.GetString("_NON_NEW_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network unavailable 的本地化字符串。
        /// </summary>
        public static string _NOTAVAILABLE_NETWORK {
            get {
                return ResourceManager.GetString("_NOTAVAILABLE_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network unavailable, proceed with the step? 的本地化字符串。
        /// </summary>
        public static string _NOTAVAILABLE_NETWORK_TIPS {
            get {
                return ResourceManager.GetString("_NOTAVAILABLE_NETWORK_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process exited 的本地化字符串。
        /// </summary>
        public static string _PROCESS_EXITED {
            get {
                return ResourceManager.GetString("_PROCESS_EXITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process started 的本地化字符串。
        /// </summary>
        public static string _PROCESS_STARTED {
            get {
                return ResourceManager.GetString("_PROCESS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read file 的本地化字符串。
        /// </summary>
        public static string _READ_FILE {
            get {
                return ResourceManager.GetString("_READ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read registry failed 的本地化字符串。
        /// </summary>
        public static string _READ_REGISTRY_FAILED {
            get {
                return ResourceManager.GetString("_READ_REGISTRY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regex match file 的本地化字符串。
        /// </summary>
        public static string _REGEX_GET_FILE {
            get {
                return ResourceManager.GetString("_REGEX_GET_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource file does not exist or is not embedded 的本地化字符串。
        /// </summary>
        public static string _RES_FILE_NOT_FIND {
            get {
                return ResourceManager.GetString("_RES_FILE_NOT_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry download 的本地化字符串。
        /// </summary>
        public static string _RETRY_DOWNLOAD {
            get {
                return ResourceManager.GetString("_RETRY_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security software is running, please close it 的本地化字符串。
        /// </summary>
        public static string _SECURITY_RUNNING {
            get {
                return ResourceManager.GetString("_SECURITY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send request 的本地化字符串。
        /// </summary>
        public static string _SEND_REQUEST {
            get {
                return ResourceManager.GetString("_SEND_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification successful 的本地化字符串。
        /// </summary>
        public static string _SUCCESS_VERIFY {
            get {
                return ResourceManager.GetString("_SUCCESS_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry successfully written 的本地化字符串。
        /// </summary>
        public static string _SUCESS_WRITE_REGISTRY {
            get {
                return ResourceManager.GetString("_SUCESS_WRITE_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        public static string _TIPS {
            get {
                return ResourceManager.GetString("_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Error 的本地化字符串。
        /// </summary>
        public static string _UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("_UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported platforms 的本地化字符串。
        /// </summary>
        public static string _UNSUPPORT_PLATFORM {
            get {
                return ResourceManager.GetString("_UNSUPPORT_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update line string 的本地化字符串。
        /// </summary>
        public static string _UPDATE_LINE {
            get {
                return ResourceManager.GetString("_UPDATE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait downloading complete 的本地化字符串。
        /// </summary>
        public static string _WAIT_DOWNLOADING {
            get {
                return ResourceManager.GetString("_WAIT_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string _WARNING {
            get {
                return ResourceManager.GetString("_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Updater disabled 的本地化字符串。
        /// </summary>
        public static string _WINDOWS_UPDATER_DISABLED {
            get {
                return ResourceManager.GetString("_WINDOWS_UPDATER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Updater enabled 的本地化字符串。
        /// </summary>
        public static string _WINDOWS_UPDATER_ENABLED {
            get {
                return ResourceManager.GetString("_WINDOWS_UPDATER_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write file 的本地化字符串。
        /// </summary>
        public static string _WRITE_FILE {
            get {
                return ResourceManager.GetString("_WRITE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write registry 的本地化字符串。
        /// </summary>
        public static string _WRITE_REGISTRY {
            get {
                return ResourceManager.GetString("_WRITE_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error writing to registry 的本地化字符串。
        /// </summary>
        public static string _WRITE_REGISTRY_FAILED {
            get {
                return ResourceManager.GetString("_WRITE_REGISTRY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow SPY 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (C) Rainbow-SPY 2019-2025, All rights reserved 的本地化字符串。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English (United States) 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NinjaMagisk Common Interface Libraries 的本地化字符串。
        /// </summary>
        public static string Protect {
            get {
                return ResourceManager.GetString("Protect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.5.0 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
