//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rox.Runtimes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rox.Runtimes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32位.
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64位.
        /// </summary>
        public static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows已激活.
        /// </summary>
        public static string _ACTIVE_WINDOWS {
            get {
                return ResourceManager.GetString("_ACTIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新行.
        /// </summary>
        public static string _ADD_NEW_LINE {
            get {
                return ResourceManager.GetString("_ADD_NEW_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回答.
        /// </summary>
        public static string _ANSWER {
            get {
                return ResourceManager.GetString("_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户取消了操作.
        /// </summary>
        public static string _CANCEL_OP {
            get {
                return ResourceManager.GetString("_CANCEL_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法激活Windows.
        /// </summary>
        public static string _CANNOT_ACTIVE_WINDOWS {
            get {
                return ResourceManager.GetString("_CANNOT_ACTIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法清空日志文件.
        /// </summary>
        public static string _CANNOT_CLEAR_LOGFILE {
            get {
                return ResourceManager.GetString("_CANNOT_CLEAR_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法禁用Windows安全中心.
        /// </summary>
        public static string _CANNOT_DISABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_CANNOT_DISABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法禁用Windows更新.
        /// </summary>
        public static string _CANNOT_DISABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_CANNOT_DISABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法禁用/启用休眠.
        /// </summary>
        public static string _CANNOT_DISENABLE_HIBERNATE {
            get {
                return ResourceManager.GetString("_CANNOT_DISENABLE_HIBERNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法启用卓越性能.
        /// </summary>
        public static string _CANNOT_ENABLE_HIGHPOWERCFG {
            get {
                return ResourceManager.GetString("_CANNOT_ENABLE_HIGHPOWERCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法启用Windows安全中心.
        /// </summary>
        public static string _CANNOT_ENABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_CANNOT_ENABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法启用Windows更新.
        /// </summary>
        public static string _CANNOT_ENABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_CANNOT_ENABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法写入日志文件.
        /// </summary>
        public static string _CANNOT_WRITE_LOGFILE {
            get {
                return ResourceManager.GetString("_CANNOT_WRITE_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空日志文件.
        /// </summary>
        public static string _CLEAR_LOGFILE {
            get {
                return ResourceManager.GetString("_CLEAR_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建目录.
        /// </summary>
        public static string _CREATE_DIRECTORY {
            get {
                return ResourceManager.GetString("_CREATE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凭据解析失败，请检查账户格式.
        /// </summary>
        public static string _CREDENTIAL_PARSE_ERROR {
            get {
                return ResourceManager.GetString("_CREDENTIAL_PARSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本.
        /// </summary>
        public static string _CURRENT_VER {
            get {
                return ResourceManager.GetString("_CURRENT_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用aria2c日志输出.
        /// </summary>
        public static string _DISABLE_ARIA2C_LOG_OUTPUT {
            get {
                return ResourceManager.GetString("_DISABLE_ARIA2C_LOG_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已禁用Windows安全中心.
        /// </summary>
        public static string _DISABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_DISABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已禁用Windows更新.
        /// </summary>
        public static string _DISABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_DISABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已禁用/启用休眠.
        /// </summary>
        public static string _DISENABLE_HIBERNATE {
            get {
                return ResourceManager.GetString("_DISENABLE_HIBERNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成.
        /// </summary>
        public static string _DOWNLOADING_COMPLETE {
            get {
                return ResourceManager.GetString("_DOWNLOADING_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载失败.
        /// </summary>
        public static string _DOWNLOADING_FAILED {
            get {
                return ResourceManager.GetString("_DOWNLOADING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载文件.
        /// </summary>
        public static string _DOWNLOADING_FILE {
            get {
                return ResourceManager.GetString("_DOWNLOADING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用aria2c日志输出.
        /// </summary>
        public static string _ENABLE_ARIA2C_LOG_OUTPUT {
            get {
                return ResourceManager.GetString("_ENABLE_ARIA2C_LOG_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已启用卓越性能.
        /// </summary>
        public static string _ENABLE_HIGHPOWERCFG {
            get {
                return ResourceManager.GetString("_ENABLE_HIGHPOWERCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已启用Windows安全中心.
        /// </summary>
        public static string _ENABLE_SECURITY_CENTER {
            get {
                return ResourceManager.GetString("_ENABLE_SECURITY_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已启用Windows更新.
        /// </summary>
        public static string _ENABLE_WINDOWS_UPDATER {
            get {
                return ResourceManager.GetString("_ENABLE_WINDOWS_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的凭据.
        /// </summary>
        public static string _ENTER_CREDENTIALS {
            get {
                return ResourceManager.GetString("_ENTER_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string _ERROR {
            get {
                return ResourceManager.GetString("_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误代码.
        /// </summary>
        public static string _ERROR_CODE {
            get {
                return ResourceManager.GetString("_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件存在.
        /// </summary>
        public static string _FILE_EXIST {
            get {
                return ResourceManager.GetString("_FILE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件已保存到.
        /// </summary>
        public static string _FILE_EXIST_PATH {
            get {
                return ResourceManager.GetString("_FILE_EXIST_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在写入文件.
        /// </summary>
        public static string _FILE_WRITING {
            get {
                return ResourceManager.GetString("_FILE_WRITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取html元素.
        /// </summary>
        public static string _FIND_HTML_CODE {
            get {
                return ResourceManager.GetString("_FIND_HTML_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析html页面文件.
        /// </summary>
        public static string _FINDING_HTML_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("_FINDING_HTML_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取32位程序下载链接.
        /// </summary>
        public static string _GET_32_LINK {
            get {
                return ResourceManager.GetString("_GET_32_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取64位程序下载链接.
        /// </summary>
        public static string _GET_64_LINK {
            get {
                return ResourceManager.GetString("_GET_64_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取aria2c参数集.
        /// </summary>
        public static string _GET_ARIA2C_ARGS {
            get {
                return ResourceManager.GetString("_GET_ARIA2C_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取aria2c退出码.
        /// </summary>
        public static string _GET_ARIA2C_EXITCODE {
            get {
                return ResourceManager.GetString("_GET_ARIA2C_EXITCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取aria2c文件路径.
        /// </summary>
        public static string _GET_ARIA2C_PATH {
            get {
                return ResourceManager.GetString("_GET_ARIA2C_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取目录.
        /// </summary>
        public static string _GET_DIRECTORY {
            get {
                return ResourceManager.GetString("_GET_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取文件.
        /// </summary>
        public static string _GET_FILE {
            get {
                return ResourceManager.GetString("_GET_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取文件夹内所有文件.
        /// </summary>
        public static string _GET_FILES_IN_DIRECTORY {
            get {
                return ResourceManager.GetString("_GET_FILES_IN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取html页面文件.
        /// </summary>
        public static string _GET_HTML {
            get {
                return ResourceManager.GetString("_GET_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取输出目录.
        /// </summary>
        public static string _GET_OUTPUT_DIRECTORY {
            get {
                return ResourceManager.GetString("_GET_OUTPUT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取输出文件名称.
        /// </summary>
        public static string _GET_OUTPUT_NAME {
            get {
                return ResourceManager.GetString("_GET_OUTPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到响应.
        /// </summary>
        public static string _GET_RESPONSE {
            get {
                return ResourceManager.GetString("_GET_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取项目资源清单.
        /// </summary>
        public static string _GET_RM_NAME {
            get {
                return ResourceManager.GetString("_GET_RM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取资源数据.
        /// </summary>
        public static string _GET_RM_OBJ {
            get {
                return ResourceManager.GetString("_GET_RM_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取系统位数.
        /// </summary>
        public static string _GET_SYSTEM_BIT {
            get {
                return ResourceManager.GetString("_GET_SYSTEM_BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取临时文件夹.
        /// </summary>
        public static string _GET_TEMP {
            get {
                return ResourceManager.GetString("_GET_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取下载链接.
        /// </summary>
        public static string _GET_URL {
            get {
                return ResourceManager.GetString("_GET_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析 Json 失败.
        /// </summary>
        public static string _JSON_PARSING_FAILED {
            get {
                return ResourceManager.GetString("_JSON_PARSING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新版本.
        /// </summary>
        public static string _LATEST_VERSION {
            get {
                return ResourceManager.GetString("_LATEST_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码长度不符合要求.
        /// </summary>
        public static string _LOGIN_ERROR_1382 {
            get {
                return ResourceManager.GetString("_LOGIN_ERROR_1382", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不符合密码策略要求.
        /// </summary>
        public static string _LOGIN_ERROR_1383 {
            get {
                return ResourceManager.GetString("_LOGIN_ERROR_1383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无密码登录失败，请启用「允许空密码本地账户登录」策略.
        /// </summary>
        public static string _LOGIN_ERROR_1385 {
            get {
                return ResourceManager.GetString("_LOGIN_ERROR_1385", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户已过期.
        /// </summary>
        public static string _LOGIN_ERROR_ACCOUNT_EXPIRED {
            get {
                return ResourceManager.GetString("_LOGIN_ERROR_ACCOUNT_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录失败: 用户名未知或密码错误。.
        /// </summary>
        public static string _LOGIN_ERROR_USER_OR_PASSWORD {
            get {
                return ResourceManager.GetString("_LOGIN_ERROR_USER_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请验证您的身份.
        /// </summary>
        public static string _LOGIN_VERIFY {
            get {
                return ResourceManager.GetString("_LOGIN_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证失败.
        /// </summary>
        public static string _LOGIN_VERIFY_ERROR {
            get {
                return ResourceManager.GetString("_LOGIN_VERIFY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建ResourceManager实例.
        /// </summary>
        public static string _NEW_RM {
            get {
                return ResourceManager.GetString("_NEW_RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新版本可用.
        /// </summary>
        public static string _NEW_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("_NEW_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本为最新版本.
        /// </summary>
        public static string _NON_NEW_VER {
            get {
                return ResourceManager.GetString("_NON_NEW_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络不可用.
        /// </summary>
        public static string _NOTAVAILABLE_NETWORK {
            get {
                return ResourceManager.GetString("_NOTAVAILABLE_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络不可用, 是否执行步骤?.
        /// </summary>
        public static string _NOTAVAILABLE_NETWORK_TIPS {
            get {
                return ResourceManager.GetString("_NOTAVAILABLE_NETWORK_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进程已退出.
        /// </summary>
        public static string _PROCESS_EXITED {
            get {
                return ResourceManager.GetString("_PROCESS_EXITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进程已启动.
        /// </summary>
        public static string _PROCESS_STARTED {
            get {
                return ResourceManager.GetString("_PROCESS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取文件.
        /// </summary>
        public static string _READ_FILE {
            get {
                return ResourceManager.GetString("_READ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取注册表时出错.
        /// </summary>
        public static string _READ_REGISTRY_FAILED {
            get {
                return ResourceManager.GetString("_READ_REGISTRY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正则表达式匹配文件.
        /// </summary>
        public static string _REGEX_GET_FILE {
            get {
                return ResourceManager.GetString("_REGEX_GET_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源文件不存在或未嵌入.
        /// </summary>
        public static string _RES_FILE_NOT_FIND {
            get {
                return ResourceManager.GetString("_RES_FILE_NOT_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试下载.
        /// </summary>
        public static string _RETRY_DOWNLOAD {
            get {
                return ResourceManager.GetString("_RETRY_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全软件运行中, 请关闭.
        /// </summary>
        public static string _SECURITY_RUNNING {
            get {
                return ResourceManager.GetString("_SECURITY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送请求.
        /// </summary>
        public static string _SEND_REQUEST {
            get {
                return ResourceManager.GetString("_SEND_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证成功.
        /// </summary>
        public static string _SUCCESS_VERIFY {
            get {
                return ResourceManager.GetString("_SUCCESS_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册表已成功写入.
        /// </summary>
        public static string _SUCESS_WRITE_REGISTRY {
            get {
                return ResourceManager.GetString("_SUCESS_WRITE_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组策略路径：计算机配置→Windows设置→安全设置→本地策略→安全选项→账户：允许空密码的本地账户登录.
        /// </summary>
        public static string _TIP_EMPTY_PASSWORD_POLICY {
            get {
                return ResourceManager.GetString("_TIP_EMPTY_PASSWORD_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft账户请输入完整邮箱（如xxx@outlook.com），开启两步验证需使用应用密码.
        /// </summary>
        public static string _TIP_MICROSOFT_ACCOUNT {
            get {
                return ResourceManager.GetString("_TIP_MICROSOFT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string _TIPS {
            get {
                return ResourceManager.GetString("_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        public static string _UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("_UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的平台.
        /// </summary>
        public static string _UNSUPPORT_PLATFORM {
            get {
                return ResourceManager.GetString("_UNSUPPORT_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新行值.
        /// </summary>
        public static string _UPDATE_LINE {
            get {
                return ResourceManager.GetString("_UPDATE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待下载完成.
        /// </summary>
        public static string _WAIT_DOWNLOADING {
            get {
                return ResourceManager.GetString("_WAIT_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string _WARNING {
            get {
                return ResourceManager.GetString("_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证窗口创建失败，请以管理员身份运行程序.
        /// </summary>
        public static string _WINDOW_CREATE_ERROR {
            get {
                return ResourceManager.GetString("_WINDOW_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 更新已被禁用.
        /// </summary>
        public static string _WINDOWS_UPDATER_DISABLED {
            get {
                return ResourceManager.GetString("_WINDOWS_UPDATER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 更新已启用.
        /// </summary>
        public static string _WINDOWS_UPDATER_ENABLED {
            get {
                return ResourceManager.GetString("_WINDOWS_UPDATER_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入文件.
        /// </summary>
        public static string _WRITE_FILE {
            get {
                return ResourceManager.GetString("_WRITE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入注册表.
        /// </summary>
        public static string _WRITE_REGISTRY {
            get {
                return ResourceManager.GetString("_WRITE_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入注册表时出错.
        /// </summary>
        public static string _WRITE_REGISTRY_FAILED {
            get {
                return ResourceManager.GetString("_WRITE_REGISTRY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow SPY.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) Rainbow-SPY 2019-2025 , All rights reserved.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon err {
            get {
                object obj = ResourceManager.GetObject("err", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rox Common Interface Libraries.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
